// This file has been generated by Py++.

#ifndef NanometerUnit_hpp__pyplusplus_wrapper
#define NanometerUnit_hpp__pyplusplus_wrapper

void register_NanometerUnit_class();

#endif//NanometerUnit_hpp__pyplusplus_wrapper
