// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_moltk.hpp"
#include "_moltk_enumerations.pypp.hpp"

namespace bp = boost::python;

void register_enumerations(){

    bp::enum_< moltk::units::DimensionIndex>("DimensionIndex")
        .value("DIMENSION_MASS", moltk::units::DIMENSION_MASS)
        .value("DIMENSION_LENGTH", moltk::units::DIMENSION_LENGTH)
        .value("DIMENSION_TIME", moltk::units::DIMENSION_TIME)
        .value("DIMENSION_CHARGE", moltk::units::DIMENSION_CHARGE)
        .value("DIMENSION_AMOUNT", moltk::units::DIMENSION_AMOUNT)
        .value("DIMENSION_ANGLE", moltk::units::DIMENSION_ANGLE)
        .value("DIMENSION_INFORMATION", moltk::units::DIMENSION_INFORMATION)
        .export_values()
        ;

}
