// This file has been generated by Py++.

#ifndef Information_hpp__pyplusplus_wrapper
#define Information_hpp__pyplusplus_wrapper

void register_Information_class();

#endif//Information_hpp__pyplusplus_wrapper
