// This file has been generated by Py++.

#ifndef InformationDimension_hpp__pyplusplus_wrapper
#define InformationDimension_hpp__pyplusplus_wrapper

void register_InformationDimension_class();

#endif//InformationDimension_hpp__pyplusplus_wrapper
