// This file has been generated by Py++.

#ifndef RadianUnit_hpp__pyplusplus_wrapper
#define RadianUnit_hpp__pyplusplus_wrapper

void register_RadianUnit_class();

#endif//RadianUnit_hpp__pyplusplus_wrapper
