// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_moltk.hpp"
#include "unitvector3d.pypp.hpp"

namespace bp = boost::python;

void register_UnitVector3D_class(){

    bp::class_< moltk::UnitVector3D >( "UnitVector3D", "\n UnitVector3D represents a direction in 3 space, and, unlike Vector3D_<>, does NOT have Units.\n", bp::init< >() )    
        .def( bp::init< moltk::UnitVector3D const & >(( bp::arg("other") )) )    
        .def( bp::init< double const &, double const &, double const & >(( bp::arg("x"), bp::arg("y"), bp::arg("z") )) )    
        .def( 
            "norm"
            , (::moltk::Real ( ::moltk::UnitVector3D::* )(  ) const)( &::moltk::UnitVector3D::norm ) )    
        .def( 
            "normSquared"
            , (::moltk::Real ( ::moltk::UnitVector3D::* )(  ) const)( &::moltk::UnitVector3D::normSquared ) )    
        .def( bp::self * bp::other< moltk::Real >() )    
        .def( bp::other< moltk::Real >() * bp::self );

}
