// This file has been generated by Py++.

#ifndef Displacement_hpp__pyplusplus_wrapper
#define Displacement_hpp__pyplusplus_wrapper

void register_Displacement_class();

#endif//Displacement_hpp__pyplusplus_wrapper
