// This file has been generated by Py++.

#ifndef LengthDimension_hpp__pyplusplus_wrapper
#define LengthDimension_hpp__pyplusplus_wrapper

void register_LengthDimension_class();

#endif//LengthDimension_hpp__pyplusplus_wrapper
