// This file has been generated by Py++.

#include "boost/python.hpp"

#include "moltk/pdb/atom.h"

#include "generated_code_msvc/atom.pypp.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(moltk){
    register_Atom_class();
}

