// This file has been generated by Py++.

#ifndef _moltk_enumerations_hpp__pyplusplus_wrapper
#define _moltk_enumerations_hpp__pyplusplus_wrapper

void register_enumerations();

#endif//_moltk_enumerations_hpp__pyplusplus_wrapper
