// This file has been generated by Py++.

#ifndef DPTableILU1_hpp__pyplusplus_wrapper
#define DPTableILU1_hpp__pyplusplus_wrapper

void register_DPTableILU1_class();

#endif//DPTableILU1_hpp__pyplusplus_wrapper
