// This file has been generated by Py++.

#ifndef PDBStructure_hpp__pyplusplus_wrapper
#define PDBStructure_hpp__pyplusplus_wrapper

void register_PDBStructure_class();

#endif//PDBStructure_hpp__pyplusplus_wrapper
