// This file has been generated by Py++.

#ifndef std_vector_int_hpp__pyplusplus_wrapper
#define std_vector_int_hpp__pyplusplus_wrapper

void register_std_vector_int_class();

#endif//std_vector_int_hpp__pyplusplus_wrapper
