// This file has been generated by Py++.

#ifndef _moltk_global_variables_hpp__pyplusplus_wrapper
#define _moltk_global_variables_hpp__pyplusplus_wrapper

void register_global_variables();

#endif//_moltk_global_variables_hpp__pyplusplus_wrapper
