// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_moltk.h"
#include "FastaSequence.pypp.hpp"

namespace bp = boost::python;

void register_FastaSequence_class(){

    { //::moltk::FastaSequence
        typedef bp::class_< moltk::FastaSequence > FastaSequence_exposer_t;
        FastaSequence_exposer_t FastaSequence_exposer = FastaSequence_exposer_t( "FastaSequence", bp::init< std::string const & >(( bp::arg("s") )) );
        bp::scope FastaSequence_scope( FastaSequence_exposer );
        bp::implicitly_convertible< std::string const &, moltk::FastaSequence >();
    }

}
