// This file has been generated by Py++.

#ifndef FastaSequence_hpp__pyplusplus_wrapper
#define FastaSequence_hpp__pyplusplus_wrapper

void register_FastaSequence_class();

#endif//FastaSequence_hpp__pyplusplus_wrapper
