// This file has been generated by Py++.

#ifndef length_dimension_hpp__pyplusplus_wrapper
#define length_dimension_hpp__pyplusplus_wrapper

void register_length_dimension_class();

#endif//length_dimension_hpp__pyplusplus_wrapper
