// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_moltk.h"
#include "nanometer_t.pypp.hpp"

namespace bp = boost::python;

void register_nanometer_t_class(){

    bp::class_< moltk::units::unit< moltk::units::length_dimension > >( "nanometer_t", "\n" )    
        .def( 
            "print_name"
            , (void (*)( ::std::basic_ostream< char, std::char_traits< char > > & ))( &::moltk::units::unit< moltk::units::length_dimension >::print_name )
            , ( bp::arg("os") ) )    
        .def( 
            "print_symbol"
            , (void (*)( ::std::basic_ostream< char, std::char_traits< char > > & ))( &::moltk::units::unit< moltk::units::length_dimension >::print_symbol )
            , ( bp::arg("os") ) )    
        .staticmethod( "print_name" )    
        .staticmethod( "print_symbol" );

}
