// This file has been generated by Py++.

#include "boost/python.hpp"
#include "indexing_suite/container_suite.hpp"
#include "indexing_suite/vector.hpp"
#include "wrap_moltk.h"
#include "std_vector_int.pypp.hpp"

namespace bp = boost::python;

void register_std_vector_int_class(){

    { //::std::vector< int >
        typedef bp::class_< std::vector< int > > std_vector_int_exposer_t;
        std_vector_int_exposer_t std_vector_int_exposer = std_vector_int_exposer_t( "std_vector_int", "\n  A standard container which offers fixed time access to\n  individual elements in any order.\n\n  fngroup Containers\n  fngroup Sequences\n\n  Meets the requirements of a <a href=tables.html#65>container</a>, a\n  <a href=tables.html#66>reversible container</a>, and a\n  <a href=tables.html#67>sequence</a>, including the\n  <a href=tables.html#68>optional sequence requirements</a> with the\n  %exception of @c push_front and @c pop_front.\n\n  In some terminology a %vector can be described as a dynamic\n  C-style array, it offers fast and efficient access to individual\n  elements in any order and saves the user from worrying about\n  memory and size allocation.  Subscripting ( @c [] ) access is\n  also provided as with C-style arrays.\n" );
        bp::scope std_vector_int_scope( std_vector_int_exposer );
        std_vector_int_exposer.def( bp::indexing::vector_suite< std::vector< int > >() );
    }

}
