// This file has been generated by Py++.

#ifndef Alignment_hpp__pyplusplus_wrapper
#define Alignment_hpp__pyplusplus_wrapper

void register_Alignment_class();

#endif//Alignment_hpp__pyplusplus_wrapper
