// This file has been generated by Py++.

#ifndef AngleDimension_hpp__pyplusplus_wrapper
#define AngleDimension_hpp__pyplusplus_wrapper

void register_AngleDimension_class();

#endif//AngleDimension_hpp__pyplusplus_wrapper
