// This file has been generated by Py++.

#ifndef QueryPositionList_hpp__pyplusplus_wrapper
#define QueryPositionList_hpp__pyplusplus_wrapper

void register_QueryPositionList_class();

#endif//QueryPositionList_hpp__pyplusplus_wrapper
