// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_moltk.hpp"
#include "rigidtransform.pypp.hpp"

namespace bp = boost::python;

void register_RigidTransform_class(){

    bp::class_< moltk::RigidTransform >( "RigidTransform", "\n RigidTransform converts one reference frame to another with rotation and translation.\n" );

}
