// This file has been generated by Py++.

#ifndef RigidTransform_hpp__pyplusplus_wrapper
#define RigidTransform_hpp__pyplusplus_wrapper

void register_RigidTransform_class();

#endif//RigidTransform_hpp__pyplusplus_wrapper
