// This file has been generated by Py++.

#ifndef Rotation3D_hpp__pyplusplus_wrapper
#define Rotation3D_hpp__pyplusplus_wrapper

void register_Rotation3D_class();

#endif//Rotation3D_hpp__pyplusplus_wrapper
