// This file has been generated by Py++.

#ifndef Biosequence_hpp__pyplusplus_wrapper
#define Biosequence_hpp__pyplusplus_wrapper

void register_Biosequence_class();

#endif//Biosequence_hpp__pyplusplus_wrapper
