// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_moltk.hpp"
#include "BitUnit.pypp.hpp"

namespace bp = boost::python;

void register_BitUnit_class(){

    bp::class_< moltk::units::Unit< moltk::units::InformationDimension >, boost::noncopyable >( "BitUnit", "\n", bp::no_init )    
        .def( 
            "get_instance"
            , (::moltk::units::Unit< moltk::units::InformationDimension > const & (*)(  ))( &::moltk::units::Unit< moltk::units::InformationDimension >::get_instance )
            , bp::return_value_policy< bp::copy_const_reference >() )    
        .def( 
            "print_name"
            , (void (*)( ::std::basic_ostream< char, std::char_traits< char > > & ))( &::moltk::units::Unit< moltk::units::InformationDimension >::print_name )
            , ( bp::arg("os") ) )    
        .def( 
            "print_symbol"
            , (void (*)( ::std::basic_ostream< char, std::char_traits< char > > & ))( &::moltk::units::Unit< moltk::units::InformationDimension >::print_symbol )
            , ( bp::arg("os") ) )    
        .staticmethod( "get_instance" )    
        .staticmethod( "print_name" )    
        .staticmethod( "print_symbol" )    
        .def( bp::other< double >() * bp::self );

}
