// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_moltk.hpp"
#include "Displacement.pypp.hpp"

namespace bp = boost::python;

void register_Displacement_class(){

    bp::class_< moltk::Vector3D_< moltk::units::Quantity< moltk::units::Unit< moltk::units::Dimension< 0, 1, 0, 0, 0, 0, 0 > >, double > > >( "Displacement", "\n Vector3D_<> is an arbitrary point or vector in 3-space.\n\n Vector3D_<> can contain Quantities with Units.\n", bp::init< >() )    
        .def( bp::init< moltk::units::Quantity< moltk::units::Unit< moltk::units::Dimension< 0, 1, 0, 0, 0, 0, 0 > >, double > const &, moltk::units::Quantity< moltk::units::Unit< moltk::units::Dimension< 0, 1, 0, 0, 0, 0, 0 > >, double > const &, moltk::units::Quantity< moltk::units::Unit< moltk::units::Dimension< 0, 1, 0, 0, 0, 0, 0 > >, double > const & >(( bp::arg("x"), bp::arg("y"), bp::arg("z") )) );

}
