// This file has been generated by Py++.

#ifndef Printable_hpp__pyplusplus_wrapper
#define Printable_hpp__pyplusplus_wrapper

void register_Printable_class();

#endif//Printable_hpp__pyplusplus_wrapper
