// This file has been generated by Py++.

#include "boost/python.hpp"
#include "indexing_suite/container_suite.hpp"
#include "indexing_suite/vector.hpp"
#include "wrap_moltk.hpp"
#include "QueryPositionList.pypp.hpp"

namespace bp = boost::python;

void register_QueryPositionList_class(){

    { //::std::vector< moltk::Aligner::QueryPosition* >
        typedef bp::class_< std::vector< moltk::Aligner::QueryPosition* > > QueryPositionList_exposer_t;
        QueryPositionList_exposer_t QueryPositionList_exposer = QueryPositionList_exposer_t( "QueryPositionList", "\n  A standard container which offers fixed time access to\n  individual elements in any order.\n\n  fngroup Containers\n  fngroup Sequences\n\n  Meets the requirements of a <a href=tables.html#65>container</a>, a\n  <a href=tables.html#66>reversible container</a>, and a\n  <a href=tables.html#67>sequence</a>, including the\n  <a href=tables.html#68>optional sequence requirements</a> with the\n  %exception of @c push_front and @c pop_front.\n\n  In some terminology a %vector can be described as a dynamic\n  C-style array, it offers fast and efficient access to individual\n  elements in any order and saves the user from worrying about\n  memory and size allocation.  Subscripting ( @c [] ) access is\n  also provided as with C-style arrays.\n" );
        bp::scope QueryPositionList_scope( QueryPositionList_exposer );
        QueryPositionList_exposer.def( bp::indexing::vector_suite< std::vector< moltk::Aligner::QueryPosition* > >::with_policies(bp::return_internal_reference< >()) );
    }

}
