// This file has been generated by Py++.

#ifndef SubstitutionMatrix_hpp__pyplusplus_wrapper
#define SubstitutionMatrix_hpp__pyplusplus_wrapper

void register_SubstitutionMatrix_class();

#endif//SubstitutionMatrix_hpp__pyplusplus_wrapper
