// This file has been generated by Py++.

#ifndef TargetPositionList_hpp__pyplusplus_wrapper
#define TargetPositionList_hpp__pyplusplus_wrapper

void register_TargetPositionList_class();

#endif//TargetPositionList_hpp__pyplusplus_wrapper
