// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_moltk.hpp"
#include "Vector3D.pypp.hpp"

namespace bp = boost::python;

void register_Vector3D_class(){

    bp::class_< moltk::Vector3D_< double > >( "Vector3D", "\n Vector3D_<> is an arbitrary point or vector in 3-space.\n\n Vector3D_<> can contain Quantities with Units.\n", bp::init< >() )    
        .def( bp::init< double const &, double const &, double const & >(( bp::arg("x"), bp::arg("y"), bp::arg("z") )) );

}
