// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_moltk.hpp"
#include "displacement.pypp.hpp"

namespace bp = boost::python;

struct Vector3D__less__moltk_scope_units_scope_Quantity_less__moltk_scope_units_scope_Unit_less__moltk_scope_units_scope_LengthDimension__greater__comma__double__greater___greater__wrapper : moltk::Vector3D_< moltk::units::Quantity< moltk::units::Unit< moltk::units::LengthDimension >, double > >, bp::wrapper< moltk::Vector3D_< moltk::units::Quantity< moltk::units::Unit< moltk::units::LengthDimension >, double > > > {

    Vector3D__less__moltk_scope_units_scope_Quantity_less__moltk_scope_units_scope_Unit_less__moltk_scope_units_scope_LengthDimension__greater__comma__double__greater___greater__wrapper(moltk::Vector3D_<moltk::units::Quantity<moltk::units::Unit<moltk::units::LengthDimension>, double> > const & arg )
    : moltk::Vector3D_<moltk::units::Quantity<moltk::units::Unit<moltk::units::LengthDimension>, double> >( arg )
      , bp::wrapper< moltk::Vector3D_< moltk::units::Quantity< moltk::units::Unit< moltk::units::LengthDimension >, double > > >(){
        // copy constructor
        
    }

    Vector3D__less__moltk_scope_units_scope_Quantity_less__moltk_scope_units_scope_Unit_less__moltk_scope_units_scope_LengthDimension__greater__comma__double__greater___greater__wrapper( )
    : moltk::Vector3D_<moltk::units::Quantity<moltk::units::Unit<moltk::units::LengthDimension>, double> >( )
      , bp::wrapper< moltk::Vector3D_< moltk::units::Quantity< moltk::units::Unit< moltk::units::LengthDimension >, double > > >(){
        // null constructor
    
    }

    Vector3D__less__moltk_scope_units_scope_Quantity_less__moltk_scope_units_scope_Unit_less__moltk_scope_units_scope_LengthDimension__greater__comma__double__greater___greater__wrapper(::moltk::units::Quantity< moltk::units::Unit< moltk::units::LengthDimension >, double > const & x, ::moltk::units::Quantity< moltk::units::Unit< moltk::units::LengthDimension >, double > const & y, ::moltk::units::Quantity< moltk::units::Unit< moltk::units::LengthDimension >, double > const & z )
    : moltk::Vector3D_<moltk::units::Quantity<moltk::units::Unit<moltk::units::LengthDimension>, double> >( boost::ref(x), boost::ref(y), boost::ref(z) )
      , bp::wrapper< moltk::Vector3D_< moltk::units::Quantity< moltk::units::Unit< moltk::units::LengthDimension >, double > > >(){
        // constructor
    
    }

};

void register_Displacement_class(){

    bp::class_< Vector3D__less__moltk_scope_units_scope_Quantity_less__moltk_scope_units_scope_Unit_less__moltk_scope_units_scope_LengthDimension__greater__comma__double__greater___greater__wrapper, bp::bases< moltk::BaseVector3D< moltk::units::Quantity< moltk::units::Unit< moltk::units::LengthDimension >, double > > > >( "Displacement", bp::init< >() )    
        .def( bp::init< moltk::units::Quantity< moltk::units::Unit< moltk::units::LengthDimension >, double > const &, moltk::units::Quantity< moltk::units::Unit< moltk::units::LengthDimension >, double > const &, moltk::units::Quantity< moltk::units::Unit< moltk::units::LengthDimension >, double > const & >(( bp::arg("x"), bp::arg("y"), bp::arg("z") )) );

}
