// This file has been generated by Py++.

#include "boost/python.hpp"
#include "indexing_suite/container_suite.hpp"
#include "indexing_suite/vector.hpp"
#include "wrap_moltk.hpp"
#include "dppositionlist.pypp.hpp"

namespace bp = boost::python;

void register_DPPositionList_class(){

    { //::std::vector< moltk::dp::DPPosition<moltk::units::Quantity<moltk::units::Unit<moltk::units::Dimension<0, 0, 0, 0, 0, 0, 1> >, double>, 1>* >
        typedef bp::class_< std::vector< moltk::dp::DPPosition<moltk::units::Quantity<moltk::units::Unit<moltk::units::Dimension<0, 0, 0, 0, 0, 0, 1> >, double>, 1>* > > DPPositionList_exposer_t;
        DPPositionList_exposer_t DPPositionList_exposer = DPPositionList_exposer_t( "DPPositionList" );
        bp::scope DPPositionList_scope( DPPositionList_exposer );
        DPPositionList_exposer.def( bp::indexing::vector_suite< std::vector< moltk::dp::DPPosition<moltk::units::Quantity<moltk::units::Unit<moltk::units::Dimension<0, 0, 0, 0, 0, 0, 1> >, double>, 1>* > >::with_policies(bp::return_internal_reference< >()) );
    }

}
