// This file has been generated by Py++.

#ifndef EString_hpp__pyplusplus_wrapper
#define EString_hpp__pyplusplus_wrapper

void register_EString_class();

#endif//EString_hpp__pyplusplus_wrapper
