// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_moltk.hpp"
#include "informationdimension.pypp.hpp"

namespace bp = boost::python;

void register_InformationDimension_class(){

    bp::class_< moltk::units::InformationDimension, bp::bases< moltk::units::Dimension > >( "InformationDimension" );

}
