// This file has been generated by Py++.

#ifndef MatrixScorer_hpp__pyplusplus_wrapper
#define MatrixScorer_hpp__pyplusplus_wrapper

void register_MatrixScorer_class();

#endif//MatrixScorer_hpp__pyplusplus_wrapper
