// This file has been generated by Py++.

#include "boost/python.hpp"
#include "indexing_suite/container_suite.hpp"
#include "indexing_suite/vector.hpp"
#include "wrap_moltk.hpp"
#include "std_vector_targetpositioni1.pypp.hpp"

namespace bp = boost::python;

void register_std_vector_TargetPositionI1_class(){

    { //::std::vector< moltk::dp::TargetPosition<moltk::units::Quantity<moltk::units::Unit<moltk::units::Dimension<0, 0, 0, 0, 0, 0, 1> >, double>, 1> const* >
        typedef bp::class_< std::vector< moltk::dp::TargetPosition<moltk::units::Quantity<moltk::units::Unit<moltk::units::Dimension<0, 0, 0, 0, 0, 0, 1> >, double>, 1> const* > > std_vector_TargetPositionI1_exposer_t;
        std_vector_TargetPositionI1_exposer_t std_vector_TargetPositionI1_exposer = std_vector_TargetPositionI1_exposer_t( "std_vector_TargetPositionI1" );
        bp::scope std_vector_TargetPositionI1_scope( std_vector_TargetPositionI1_exposer );
        std_vector_TargetPositionI1_exposer.def( bp::indexing::vector_suite< std::vector< moltk::dp::TargetPosition<moltk::units::Quantity<moltk::units::Unit<moltk::units::Dimension<0, 0, 0, 0, 0, 0, 1> >, double>, 1> const* > >::with_policies(bp::return_internal_reference< >()) );
    }

}
