// This file has been generated by Py++.

#include "boost/python.hpp"
#include "indexing_suite/container_suite.hpp"
#include "indexing_suite/vector.hpp"
#include "wrap_moltk.hpp"
#include "targetpositionlist.pypp.hpp"

namespace bp = boost::python;

void register_TargetPositionList_class(){

    { //::std::vector< moltk::Aligner::TargetPosition* >
        typedef bp::class_< std::vector< moltk::Aligner::TargetPosition* > > TargetPositionList_exposer_t;
        TargetPositionList_exposer_t TargetPositionList_exposer = TargetPositionList_exposer_t( "TargetPositionList" );
        bp::scope TargetPositionList_scope( TargetPositionList_exposer );
        TargetPositionList_exposer.def( bp::indexing::vector_suite< std::vector< moltk::Aligner::TargetPosition* > >::with_policies(bp::return_internal_reference< >()) );
    }

}
