// This file has been generated by Py++.

#ifndef UnitVector3D_hpp__pyplusplus_wrapper
#define UnitVector3D_hpp__pyplusplus_wrapper

void register_UnitVector3D_class();

#endif//UnitVector3D_hpp__pyplusplus_wrapper
