// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_moltk.hpp"
#include "basevector3d_double.pypp.hpp"

namespace bp = boost::python;

void register_BaseVector3D_double_class(){

    bp::class_< moltk::BaseVector3D< double > >( "BaseVector3D_double", bp::init< >() )    
        .def( bp::init< double const &, double const &, double const & >(( bp::arg("x"), bp::arg("y"), bp::arg("z") )) )    
        .def( 
            "norm"
            , (double ( ::moltk::BaseVector3D<double>::* )(  ) const)( &::moltk::BaseVector3D< double >::norm ) )    
        .def( bp::self != bp::self )    
        .def( bp::self == bp::self )    
        .def( 
            "__getitem__"
            , (double const & ( ::moltk::BaseVector3D<double>::* )( ::size_t ) const)( &::moltk::BaseVector3D< double >::operator[] )
            , ( bp::arg("i") )
            , bp::return_value_policy< bp::copy_const_reference >() )    
        .def( 
            "size"
            , (::size_t ( ::moltk::BaseVector3D<double>::* )(  ) const)( &::moltk::BaseVector3D< double >::size ) )    
        .def( 
            "x"
            , (double const & ( ::moltk::BaseVector3D<double>::* )(  ) const)( &::moltk::BaseVector3D< double >::x )
            , bp::return_value_policy< bp::copy_const_reference >() )    
        .def( 
            "y"
            , (double const & ( ::moltk::BaseVector3D<double>::* )(  ) const)( &::moltk::BaseVector3D< double >::y )
            , bp::return_value_policy< bp::copy_const_reference >() )    
        .def( 
            "z"
            , (double const & ( ::moltk::BaseVector3D<double>::* )(  ) const)( &::moltk::BaseVector3D< double >::z )
            , bp::return_value_policy< bp::copy_const_reference >() )    
        .def_readonly( "SIZE", moltk::BaseVector3D< double >::SIZE );

}
