// This file has been generated by Py++.

#ifndef BaseBiosequence_hpp__pyplusplus_wrapper
#define BaseBiosequence_hpp__pyplusplus_wrapper

void register_BaseBiosequence_class();

#endif//BaseBiosequence_hpp__pyplusplus_wrapper
