// This file has been generated by Py++.

#ifndef BaseDisplacement_hpp__pyplusplus_wrapper
#define BaseDisplacement_hpp__pyplusplus_wrapper

void register_BaseDisplacement_class();

#endif//BaseDisplacement_hpp__pyplusplus_wrapper
