// This file has been generated by Py++.

#ifndef BaseVector3D_double_hpp__pyplusplus_wrapper
#define BaseVector3D_double_hpp__pyplusplus_wrapper

void register_BaseVector3D_double_class();

#endif//BaseVector3D_double_hpp__pyplusplus_wrapper
