// This file has been generated by Py++.

#ifndef BiosequenceResidue_hpp__pyplusplus_wrapper
#define BiosequenceResidue_hpp__pyplusplus_wrapper

void register_BiosequenceResidue_class();

#endif//BiosequenceResidue_hpp__pyplusplus_wrapper
