// This file has been generated by Py++.

#ifndef DPPositionList_hpp__pyplusplus_wrapper
#define DPPositionList_hpp__pyplusplus_wrapper

void register_DPPositionList_class();

#endif//DPPositionList_hpp__pyplusplus_wrapper
