// This file has been generated by Py++.

#ifndef DPTableILG1_hpp__pyplusplus_wrapper
#define DPTableILG1_hpp__pyplusplus_wrapper

void register_DPTableILG1_class();

#endif//DPTableILG1_hpp__pyplusplus_wrapper
