// This file has been generated by Py++.

#include "boost/python.hpp"
#include "indexing_suite/container_suite.hpp"
#include "indexing_suite/vector.hpp"
#include "wrap_moltk.hpp"
#include "tabletype.pypp.hpp"

namespace bp = boost::python;

void register_TableType_class(){

    { //::std::vector< std::vector< moltk::dp::DPCell<moltk::units::Quantity<moltk::units::Unit<moltk::units::Dimension<0, 0, 0, 0, 0, 0, 1> >, double>, (moltk::dp::DPAlignGapping)0, 1> > >
        typedef bp::class_< std::vector< std::vector< moltk::dp::DPCell<moltk::units::Quantity<moltk::units::Unit<moltk::units::Dimension<0, 0, 0, 0, 0, 0, 1> >, double>, (moltk::dp::DPAlignGapping)0, 1> > > > TableType_exposer_t;
        TableType_exposer_t TableType_exposer = TableType_exposer_t( "TableType" );
        bp::scope TableType_scope( TableType_exposer );
        TableType_exposer.def( bp::indexing::vector_suite< std::vector< std::vector< moltk::dp::DPCell<moltk::units::Quantity<moltk::units::Unit<moltk::units::Dimension<0, 0, 0, 0, 0, 0, 1> >, double>, (moltk::dp::DPAlignGapping)0, 1> > > >() );
    }

}
