// This file has been generated by Py++.

#ifndef TableType_hpp__pyplusplus_wrapper
#define TableType_hpp__pyplusplus_wrapper

void register_TableType_class();

#endif//TableType_hpp__pyplusplus_wrapper
