// This file has been generated by Py++.

#include "boost/python.hpp"

#include "/Users/brunsc/svn/moltk/include/moltk/pdb/Atom.h"

#include "generated_code/Atom.pypp.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(moltk){
    register_Atom_class();
}

