// This file has been generated by Py++.

#include "boost/python.hpp"
#include "c:/users/cmbruns/svn/moltk/include/moltk/pdb/atom.h"
#include "atom.pypp.hpp"

namespace bp = boost::python;

void register_Atom_class(){

    bp::class_< moltk::pdb::Atom >( "Atom" )    
        .def( 
            "foo"
            , (int ( ::moltk::pdb::Atom::* )(  ) const)( &::moltk::pdb::Atom::foo ) );

}
