// This file has been generated by Py++.

#include "boost/python.hpp"

#include "c:/users/cmbruns/svn/moltk/include/moltk/pdb/atom.h"

#include "generated_code/atom.pypp.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(moltk){
    register_Atom_class();
}

