// This file has been generated by Py++.

#include "boost/python.hpp"

#include "wrap_moltk.h"

#include "generated_code_gcc/Aligner.pypp.hpp"

#include "generated_code_gcc/Alignment.pypp.hpp"

#include "generated_code_gcc/BaseBiosequence.pypp.hpp"

#include "generated_code_gcc/Biosequence.pypp.hpp"

#include "generated_code_gcc/Information.pypp.hpp"

#include "generated_code_gcc/Printable.pypp.hpp"

#include "generated_code_gcc/Structure.pypp.hpp"

#include "generated_code_gcc/_moltk_free_functions.pypp.hpp"

#include "generated_code_gcc/_moltk_global_variables.pypp.hpp"

#include "generated_code_gcc/bit_t.pypp.hpp"

#include "generated_code_gcc/dimension.pypp.hpp"

#include "generated_code_gcc/information_dimension.pypp.hpp"

#include "generated_code_gcc/length_dimension.pypp.hpp"

#include "generated_code_gcc/nanometer_t.pypp.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(_moltk){
    register_Aligner_class();

    register_Printable_class();

    register_Alignment_class();

    register_BaseBiosequence_class();

    register_Biosequence_class();

    register_Structure_class();

    register_dimension_class();

    register_information_dimension_class();

    register_length_dimension_class();

    register_Information_class();

    register_bit_t_class();

    register_nanometer_t_class();

    register_global_variables();

    register_free_functions();
}

