// This file has been generated by Py++.

#ifndef information_dimension_hpp__pyplusplus_wrapper
#define information_dimension_hpp__pyplusplus_wrapper

void register_information_dimension_class();

#endif//information_dimension_hpp__pyplusplus_wrapper
