// This file has been generated by Py++.

#include "boost/python.hpp"

#include "/Users/brunsc/svn/moltk/c++/include/moltk/Atom.h"

#include "generated_code_gcc/Atom.pypp.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(moltk){
    register_Atom_class();
}

