// This file has been generated by Py++.

#ifndef moltk_global_variables_hpp__pyplusplus_wrapper
#define moltk_global_variables_hpp__pyplusplus_wrapper

void register_global_variables();

#endif//moltk_global_variables_hpp__pyplusplus_wrapper
