// This file has been generated by Py++.

#ifndef nanometer_t_hpp__pyplusplus_wrapper
#define nanometer_t_hpp__pyplusplus_wrapper

void register_nanometer_t_class();

#endif//nanometer_t_hpp__pyplusplus_wrapper
