// This file has been generated by Py++.

#ifndef Structure_hpp__pyplusplus_wrapper
#define Structure_hpp__pyplusplus_wrapper

void register_Structure_class();

#endif//Structure_hpp__pyplusplus_wrapper
