// This file has been generated by Py++.

#include "boost/python.hpp"

#include "wrap_moltk.h"

#include "generated_code_msvc/_moltk_global_variables.pypp.hpp"

#include "generated_code_msvc/aligner.pypp.hpp"

#include "generated_code_msvc/alignment.pypp.hpp"

#include "generated_code_msvc/basebiosequence.pypp.hpp"

#include "generated_code_msvc/biosequence.pypp.hpp"

#include "generated_code_msvc/bit_unit.pypp.hpp"

#include "generated_code_msvc/information.pypp.hpp"

#include "generated_code_msvc/information_dimension.pypp.hpp"

#include "generated_code_msvc/length_dimension.pypp.hpp"

#include "generated_code_msvc/nanometer_unit.pypp.hpp"

#include "generated_code_msvc/printable.pypp.hpp"

#include "generated_code_msvc/structure.pypp.hpp"

#include "generated_code_msvc/unit_less__moltk_scope_units_scope_information_dimension__greater_.pypp.hpp"

#include "generated_code_msvc/unit_less__moltk_scope_units_scope_length_dimension__greater_.pypp.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(_moltk){
    register_Aligner_class();

    register_Printable_class();

    register_Alignment_class();

    register_BaseBiosequence_class();

    register_Biosequence_class();

    register_Structure_class();

    register_unit_less__moltk_scope_units_scope_information_dimension__greater__class();

    register_bit_unit_class();

    register_information_dimension_class();

    register_length_dimension_class();

    register_unit_less__moltk_scope_units_scope_length_dimension__greater__class();

    register_nanometer_unit_class();

    register_Information_class();

    register_global_variables();
}

