// This file has been generated by Py++.

#ifndef nanometer_unit_hpp__pyplusplus_wrapper
#define nanometer_unit_hpp__pyplusplus_wrapper

void register_nanometer_unit_class();

#endif//nanometer_unit_hpp__pyplusplus_wrapper
