// This file has been generated by Py++.

#ifndef PdbStructure_hpp__pyplusplus_wrapper
#define PdbStructure_hpp__pyplusplus_wrapper

void register_PdbStructure_class();

#endif//PdbStructure_hpp__pyplusplus_wrapper
