// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_moltk.h"
#include "unit_less__moltk_scope_units_scope_information_dimension__greater_.pypp.hpp"

namespace bp = boost::python;

void register_unit_less__moltk_scope_units_scope_information_dimension__greater__class(){

    bp::class_< moltk::units::unit< moltk::units::information_dimension > >( "unit_less__moltk_scope_units_scope_information_dimension__greater_", "\n" );

}
