// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_moltk.h"
#include "alignment.pypp.hpp"

namespace bp = boost::python;

void register_Alignment_class(){

    bp::class_< moltk::Alignment >( "Alignment" );

}
