// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_moltk.h"
#include "biosequenceresidue.pypp.hpp"

namespace bp = boost::python;

struct BiosequenceResidue_wrapper : moltk::BiosequenceResidue, bp::wrapper< moltk::BiosequenceResidue > {

    BiosequenceResidue_wrapper(char oneLetterCodeParam, int residueNumberParam )
    : moltk::BiosequenceResidue( oneLetterCodeParam, residueNumberParam )
      , bp::wrapper< moltk::BiosequenceResidue >(){
        // constructor
    
    }

    BiosequenceResidue_wrapper(::moltk::BiosequenceResidue const & rhs )
    : moltk::BiosequenceResidue( boost::ref(rhs) )
      , bp::wrapper< moltk::BiosequenceResidue >(){
        // copy constructor
    
    }

    virtual char getOneLetterCode(  ) const  {
        if( bp::override func_getOneLetterCode = this->get_override( "getOneLetterCode" ) )
            return func_getOneLetterCode(  );
        else{
            return this->moltk::BiosequenceResidue::getOneLetterCode(  );
        }
    }
    
    char default_getOneLetterCode(  ) const  {
        return moltk::BiosequenceResidue::getOneLetterCode( );
    }

    virtual int getResidueNumber(  ) const  {
        if( bp::override func_getResidueNumber = this->get_override( "getResidueNumber" ) )
            return func_getResidueNumber(  );
        else{
            return this->moltk::BiosequenceResidue::getResidueNumber(  );
        }
    }
    
    int default_getResidueNumber(  ) const  {
        return moltk::BiosequenceResidue::getResidueNumber( );
    }

};

void register_BiosequenceResidue_class(){

    bp::class_< BiosequenceResidue_wrapper, bp::bases< moltk::BaseBiosequence::BaseResidue > >( "BiosequenceResidue", bp::init< char, int >(( bp::arg("oneLetterCodeParam"), bp::arg("residueNumberParam") )) )    
        .def( bp::init< moltk::BiosequenceResidue const & >(( bp::arg("rhs") )) )    
        .def( 
            "getOneLetterCode"
            , (char ( ::moltk::BiosequenceResidue::* )(  ) const)(&::moltk::BiosequenceResidue::getOneLetterCode)
            , (char ( BiosequenceResidue_wrapper::* )(  ) const)(&BiosequenceResidue_wrapper::default_getOneLetterCode) )    
        .def( 
            "getResidueNumber"
            , (int ( ::moltk::BiosequenceResidue::* )(  ) const)(&::moltk::BiosequenceResidue::getResidueNumber)
            , (int ( BiosequenceResidue_wrapper::* )(  ) const)(&BiosequenceResidue_wrapper::default_getResidueNumber) );

}
