// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_moltk.h"
#include "bit_unit.pypp.hpp"

namespace bp = boost::python;

void register_bit_unit_class(){

    bp::class_< moltk::units::bit_unit >( "bit_unit" )    
        .def( bp::other< moltk::Real >() * bp::self );

}
