// This file has been generated by Py++.

#ifndef dimension_hpp__pyplusplus_wrapper
#define dimension_hpp__pyplusplus_wrapper

void register_dimension_class();

#endif//dimension_hpp__pyplusplus_wrapper
