// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_moltk.h"
#include "dimension.pypp.hpp"

namespace bp = boost::python;

void register_dimension_class(){

    bp::class_< moltk::units::dimension >( "dimension", "\n" );

}
