// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_moltk.h"
#include "lengthdimension.pypp.hpp"

namespace bp = boost::python;

void register_LengthDimension_class(){

    bp::class_< moltk::units::LengthDimension, bp::bases< moltk::units::Dimension > >( "LengthDimension" );

}
