// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_moltk.h"
#include "length_dimension.pypp.hpp"

namespace bp = boost::python;

void register_length_dimension_class(){

    bp::class_< moltk::units::length_dimension, bp::bases< moltk::units::dimension > >( "length_dimension" );

}
