// This file has been generated by Py++.

#include "boost/python.hpp"

#include "wrap_moltk.h"

#include "generated_code_msvc/structure.pypp.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(moltk){
    register_Structure_class();
}

